[workspace]
members = ["component-macro", "."]

[package]
name = "npu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
component-macro = { path = "./component-macro" }
